name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Write .env from Secrets (includes DATABASE_URL for Prisma)
      - name: Write .env
        run: |
          cat > .env << 'EOF'
          # Prisma
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          # keep your alias if your app uses it too
          LIVE_DATABASE_URL=${{ secrets.LIVE_DATABASE_URL }}
          # App
          NODE_ENV=production
          PORT=${{ secrets.PORT }}
          API_PREFIX=${{ secrets.API_PREFIX }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          # Mail
          MAIL_SERVICE=${{ secrets.MAIL_SERVICE }}
          MAIL_HOST=${{ secrets.MAIL_HOST }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}
          MAIL_PORT=${{ secrets.MAIL_PORT }}
          MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}
          EOF

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install deps
        run: npm ci

      # Prisma must see DATABASE_URL in .env
      - name: Prisma generate & migrate
        run: |
          npx prisma generate
          # Use migrate deploy if you use migrations, otherwise db push
          npx prisma migrate deploy || npx prisma db push

      # Ensure PM2 exists on the runner
      - name: Ensure PM2 installed
        run: |
          which pm2 || sudo npm i -g pm2

      # Start first time or reload if already running; also refresh env
      - name: Start/Reload app with PM2
        run: |
          # Name your app so subsequent restarts work
          if pm2 describe ollie-backend > /dev/null; then
            pm2 reload ollie-backend --update-env
          else
            pm2 start index.js --name ollie-backend
          fi
          pm2 save

      # Optional: quick health check/logs
      - name: PM2 status and last logs
        run: |
          pm2 status
          pm2 logs ollie-backend --lines 50
